// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYXpy8ZeklcrMKeE4NxG6wE1W-k_HV2LI',
    appId: '1:386585841225:web:7439ac66068130b2dbb998',
    messagingSenderId: '386585841225',
    projectId: 'in-lab-activity-989b1',
    authDomain: 'in-lab-activity-989b1.firebaseapp.com',
    storageBucket: 'in-lab-activity-989b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulto818syOeyJR-q66fBEtGp4_qZxAH0',
    appId: '1:386585841225:android:c748c69bba629a84dbb998',
    messagingSenderId: '386585841225',
    projectId: 'in-lab-activity-989b1',
    storageBucket: 'in-lab-activity-989b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg4--G-AsnD9R9UGtypHKEC8e9ojlJkJ0',
    appId: '1:386585841225:ios:fdb61e8e184819cbdbb998',
    messagingSenderId: '386585841225',
    projectId: 'in-lab-activity-989b1',
    storageBucket: 'in-lab-activity-989b1.appspot.com',
    iosClientId: '386585841225-q5tgtkq0hbph150min91o0jgetd3ekd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.inLabActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg4--G-AsnD9R9UGtypHKEC8e9ojlJkJ0',
    appId: '1:386585841225:ios:fdb61e8e184819cbdbb998',
    messagingSenderId: '386585841225',
    projectId: 'in-lab-activity-989b1',
    storageBucket: 'in-lab-activity-989b1.appspot.com',
    iosClientId: '386585841225-q5tgtkq0hbph150min91o0jgetd3ekd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.inLabActivity',
  );
}
